In [2]:
import numpy as np

The Basics

In [3]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[1.0,7.0],
              [2.0, 4.0]])
print(b)

[[1. 7.]
 [2. 4.]]


In [9]:
print(a.ndim)
print(b.ndim)

1
2


In [11]:
print(a.shape)
print(b.shape)

(3,)
(2, 2)


In [15]:
print(a.dtype)
print(b.dtype)

int64
float64


In [20]:
#to specify the datatype:
a= np.array([1,2,3], dtype = 'int32')
print(a.dtype)

#itemsize gives number of bytes in one datatype
print(a.itemsize)

int32
4


In [22]:
#get total size
print(a.size*a.itemsize)
print(a.nbytes)

12
12


Accesing/Changing specific rows, columns, elements etc

In [29]:
a = np.array([[1,2,3,4,5,6,7],
             [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [32]:
#get a specific element
print (a[1, 5])
print (a[0,-2])

13
6


In [33]:
#get a specific row
print(a[0,:])

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
print(a[:,2])

[ 3 10]


In [43]:
#[startindex:endindex:stepsize]
print(a[1,1:6:2])

[ 9 11 13]


In [49]:
a = np.array([[1,2,3,4,5,6,7],
             [8,9,10,11,12,13,14]])

a[1,5] = 20
print(a)

a[:,3] = 30
print(a)

a[:,3] = [40,50]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  3 30  5  6  7]
 [ 8  9 10 30 12 20 14]]
[[ 1  2  3 40  5  6  7]
 [ 8  9 10 50 12 20 14]]


3-D Example

In [4]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
#get an element(work outside in)
b[0,0,1]

2

Initializing different types of Arrays

In [8]:
#All 0s matrix
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
a = np.ones((4,3,4))
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [13]:
#Any other number
a = np.full((2,2), 90)
print(a)

[[90 90]
 [90 90]]


In [17]:
#Random numbers
a = np.random.rand(3,3)
a
# np.randome.rand_sample to give shape as input

array([[0.51902862, 0.66160862, 0.41556892],
       [0.32112814, 0.02304682, 0.50288945],
       [0.10582544, 0.51717021, 0.24058885]])

In [23]:
#Random integer value

np.random.randint(-4, 7, size=(3,3))

array([[ 1,  5, -3],
       [ 4, -4, -2],
       [ 2,  2,  0]])

In [25]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


Challange problem 1

In [33]:
arr = np.zeros((5,5))
arr[0,:] = 1
arr[4,:] = 1
arr[:,0] = 1
arr[:,4] = 1
arr[2,2] = 9
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays

In [35]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [38]:
a[0] = 1
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


Mathematics

In [40]:
#elementwise arithmatics

a = np.array([1,2,3,4])
print(a +2)


[3 4 5 6]


In [43]:
#take sin of all the values
print (np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


Linear Algebra

In [45]:
a = np.ones((2,3))
print (a)

b = np.full((3,2), 2)
print(b)

c = np.matmul(a, b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [47]:
c = np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [50]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
np.min(stats, axis=1)
#the min in every row

array([1, 4])

In [57]:
np.max(stats)

6

In [61]:
np.sum(stats, axis=0)

array([5, 7, 9])

Reorganizing Arrays

In [69]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [72]:
#Vetically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack((v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
#Horizontal stacking
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Miscellaneous

In [78]:
#Boolean masking and advanced indexing
stats[stats > 2]

array([3, 4, 5, 6])

In [79]:
#You can index with a list in numpy
a = np.array([2,3,6,44,56,8,1,9])
a[[1,3,6]]

array([ 3, 44,  1])

In [83]:
np.any(stats>4, axis=0)
#Use all instead of any when you want to which rows/columns have all the values satisfying some condition.

array([False,  True,  True])